name = "MatsubaraFunctions"
uuid = "3b93aed6-d40a-4520-b131-eee49889bcc0"
authors = ["Dominik Kiese <dkiese1308.physik@gmail.com>"]
version = "0.1.0"

[deps]
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
